name: Android Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /opt/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Install Android SDK (cli tools)
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: '33.0.2'

      - name: Install dependencies
        run: npm ci

      - name: Build web assets
        run: npm run build:web

      - name: Install Capacitor & sync
        run: |
          npm install @capacitor/cli @capacitor/core @capacitor/android --no-save
          npx cap sync android

      - name: Add keystore (optional)
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          echo "Writing keystore"
          mkdir -p android/app
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
          cat > android/keystore.properties <<EOF
storeFile=keystore.jks
storePassword=${{ secrets.KEYSTORE_PASSWORD }}
keyAlias=${{ secrets.KEY_ALIAS }}
keyPassword=${{ secrets.KEY_PASSWORD }}
EOF

      - name: Build Android Release (assembleRelease)
        working-directory: android
        run: |
          chmod +x gradlew || true
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK/AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: |
            android/app/build/outputs/**/*.aab
            android/app/build/outputs/**/*.apk

